### ISSUE TITLE
How can I use pypi-mirror behind a proxy?

### ISSUE THREAD

**Issue by tt2000** [montag451/pypi-mirror#13]
If I use `pip` to download a package, I add `--proxy http://proxy.url:port`. Is there a similar option for `pypi-mirror`?

**Comment by montag451** [comment]
Hi @tt2000,

For the moment there is no way to specify a proxy using a command line switch but I will add one since it's something pretty common to be behind a corporate proxy. For the moment, your best shot is to try to specify the proxy using an environment variable (HTTP_PROXY and/or HTTPS_PROXY)

**Comment by montag451** [comment]
I've added a `--proxy` option to the `download` command. Could you test it? If it's OK for you I will publish a new version on PyPI

**Comment by tt2000** [comment]
How can I test it? Just cloning your master branch and running e. g. `python .\pypi_mirror.py download -d test_download --proxy http://proxy.url:1234 numpy` throws errors (not sure if related to proxy). Do I have to _install_ it differently? It seems to try to install dependencies:
```
Collecting numpy
  Using cached numpy-1.21.2.zip (10.3 MB)
  Installing build dependencies ... error
```
Should it not just download the dependencies instead of installing them?

**Comment by montag451** [comment]
`pypi-mirror` uses `pip` under the hood to download a package and its dependencies. When `pip` downloads a source distribution (e.g numpy-1.21.2.zip) it runs the setup script of the package to find out the dependencies of the package because source distributions do not have the `Requires-Dist` field in their metadata file (i.e the `PKG-INFO` inside the tarball or the zip file, see https://github.com/pypa/setuptools/issues/1805). Setup scripts can do a lot of things and the setup script of `numpy` is a pretty complicated one. To prevent this kind of things to happen, I strongly advise you to download only binary distribution (i.e wheel files) using the `-b` option of the `download` command:
``` sh
python .\pypi_mirror.py download -d test_download --proxy http://proxy.url:1234 -b numpy
```

**Comment by johnziebro** [comment]
Just noting that using the -b flag also allowed mirroring of the osmnx module, which has a complicated install process with pip (considered experimental) and conda installation is generally recommended. Flagging binary also significantly speeds up the process by bypassing local building.

**Comment by tt2000** [comment]
@montag451 Testing was successful, I can confirm that the new `proxy` argument works. Thx for the very fast responses and good service!

**Comment by montag451** [comment]
@tt2000 Perfect, I will publish a new version of the package on PyPI. Thx for the bug report and the testing! I will close this issue as soon as the new version is published.

**Comment by montag451** [comment]
I've published a [new version](https://pypi.org/project/python-pypi-mirror/4.0.7/) on PyPI so I will close this issue. Thx again for the bug report and the testing!
