### ISSUE TITLE
list command returns incorrect package name

### ISSUE THREAD

**Issue by jemajet** [montag451/pypi-mirror#26]
For example, after using pypi-mirror to download [pandas-plink](https://pypi.org/project/pandas-plink/), the `pypi-mirror list` command returns as pandas_plink instead of pandas-plink. I think this is because the list command doesn't use the `norm_name` attribute from the metadata. Would it be possible to change this/add a flag to receive the names as norm names instead of the downloaded tar file names?

**Comment by montag451** [comment]
Hi @jemajet 

Thx for the bug report. In fact the problem comes from the metadata of the `panda-plink` package. If you look at their [setup.cfg](https://github.com/limix/pandas-plink/blob/main/setup.cfg) you will see that the name of the package is advertised as `pandas_plink`  not `pandas-plink`. So the metadata file generated for the package (the `PKG-INFO` file used by `pypi-mirror`) contains `pandas_plink` as the name. So the best thing I can do is to add a flag to force the use of the `norm_name` instead of the name.

**Comment by montag451** [comment]
Done in [66a4428](https://github.com/montag451/pypi-mirror/commit/66a4428ada95ce200ae6fe23a800f5a9b161aa5a)

**Comment by jemajet** [comment]
@montag451 Thanks for the quick response! The new flag seems like exactly what I need, so I appreciate you taking the time to help!

**Comment by montag451** [comment]
Thx for the quick feedback. I will publish a new release on PyPI soon

**Comment by jemajet** [comment]
Do you know how soon the new pypi release should come out?

**Comment by montag451** [comment]
I've just done it. Check out [PyPI](https://pypi.org/project/python-pypi-mirror/)
