### ISSUE TITLE
getting Installing build dependencies ... error  for some package

### ISSUE THREAD

**Issue by Tonyttlab** [montag451/pypi-mirror#27]
For example:

I have Python 3.10.5 on Windows server 2016

Run below command to download matplotlib

pypi-mirror download -d downloads matplotlib

I am getting these error:

       note: This error originates from a subprocess, and is likely not a problem with pip.
          ERROR: Failed building wheel for Cython
          Running setup.py clean for Cython
        Failed to build Cython
        ERROR: Could not build wheels for Cython, which is required to install pyproject.toml-based projects
        [end of output]

Could you please help?

**Comment by montag451** [comment]
Can you try:
``` python
pypi-mirror download -d downloads -b matplotlib
```

**Comment by Tonyttlab** [comment]
It works with option -b. 

what is option -b for? Should I use it for downloading other package?

Thank you.

**Comment by montag451** [comment]
The `-b` flag instructs `pip` to download prebuilt binary wheel when possible. The advantage of prebuilt binary is that it requires no compiler and libraries installed on the machine where `pip` is running. Some project like [PyTorch](https://pypi.org/project/torch/#files) are only available as prebuilt binary wheels because building them from source is too complicated and take a lot of times.
